a = "i am sai kiran,welcome to my world"
print (a.capitalize ())
print (a.center (10))
print (a.encode ())
print (a.endswith ("d"))
print (a.endswith ("s"))
print (a.count ("a"))
print (a.find ("welcome"))
print (a.index ("welcome"))
print (a.isalnum ())
print (a.isalpha ())
print (a.swapcase ())
print (a.split (","))
print (a.replace ("world", "palace"))